## 仮注文詳細のAPIを叩く
注文ページに表示する仮注文詳細のAPIを叩いて、コンソールに表示するまでを実装します。

### API関数を実装する
フロントエンドからAPIを叩くためにまず必要なmoduleは`src/apis/line_foods.js`に定義していきます。

**src/apis/line_foods.js**
```js:src/apis/line_foods.js
export const fetchLineFoods = () => {
  return axios.get(lineFoods)
  .then(res => {
    return res.data
  })
  .catch((e) => { throw e; })
};
```

`lineFoods`はURL文字列で、`http://localhost:3000/api/v1/line_foods`。
ここではURLに対して`axios.get()`でGETリクエストを投げています。
そしてその返り値は例のごとく`then ... catch ...`で成功/失敗した場合にそれぞれのレスポンスを返り値としています。

#### JavaScriptのthrow文
ここで一つ普段気にしないけど、意外と大事なJavaScriptの例外処理について。
それは`throw`文についてです。

`throw hoge;`とすることで`hoge`という値で例外を生成します。
あえてユーザーがエラーを定義して、そこで停止させたい場合があります。
そのような時に`throw`を使ってエラー(例外)を発生させる。

```js
var hoge = 1;
throw hoge;
console.log(hoge);
```

赤文字のエラーが発生し、`console.log(hoge);`は実行されません。
これは`throw hoge;`で処理が停止するためです。
`throw hoge;`ではなく別の値を使って`throw 1;`としても同様です。
`throw`で例外が発生すると、そこでプログラムは停止します。

さらに、`throw`と合わせて使われるのが`Error`オブジェクトです。
```js
throw new Error('エラーメッセージを引数に渡すことができます')
```

こうすることで、APIから返ってきたエラーメッセージを`Error`オブジェクトの中身に入れることができます。
それを`throw`するので、ここで例外が発生します。

単にエラー文を表示させるだけなら`console.error('エラー')`でも出来ます。
`throw`は`try ... catch ...`や今回のように`then ... catch ...`と併用することでその効果を発揮します。

```js
try {
  console.log("正常な処理開始...")
  throw new Error("なにかエラーが起きました！");  // ここで例外発生させると
  console.log("処理が完了しました");            // ここは表示されません。
} catch(e) {                                   // eという変数名でErrorオブジェクトを捕まえて
  console.log("エラーの内容は...");
  console.error(e);　　　　　　　　　　　　　　　 // そしてここで出力されます
}
```

すると、コメントアウトした通り`throw`したところで処理は停止し、`catch`に入ります。
そして`e`という変数名で`Error`オブジェクトを受け取って、最終的に`console.error(e)`で出力しています。
これは`then ... catch ...`でも同様です。

### Orders.jsx
**src/containers/Orders.jsx**
```js:src/containers/Orders.jsx
// --- 次でuseEffectを追加 ---
import React, { Fragment, useEffect } from 'react';

// --- ここから追加 ---
import { fetchLineFoods } from '../apis/line_foods';
// --- ここまで追加 ---

export const Orders = () => {

// --- ここから追加 ---
  useEffect(() => {
    fetchLineFoods()
      .then((data) =>
        console.log(data)
      )
      .catch((e) => console.error(e));
  }, []);
// --- ここまで追加 ---

  return (
    <Fragment>
      注文画面
    </Fragment>
  )
}
```